import csv
from pathlib import Path

from python.relaynet.contextual_reasoner import ContextualReasoner


class RelayKnowledgeGraph:
    """
    Temporal Knowledge Graph for RelayNet.

    Stores:
    1. Raw temporal relay observations.
    2. Derived contextual reasoning knowledge.

    The contextual reasoning is generated by the existing
    lightweight rule-based ContextualReasoner.
    """

    def __init__(self):
        self.triples = []
        self.reasoner = ContextualReasoner()

    def add_triple(self, subject, predicate, object_value):
        self.triples.append(
            (subject, predicate, object_value)
        )

    def add_relay_observation(self, row):
        relay_id = row["relay_id"]
        time_step = row["time_step"]

        relay = f"Relay:{relay_id}"
        state = f"State:{relay_id}:T{time_step}"

        # --------------------------------------------------
        # Raw temporal observation triples
        # --------------------------------------------------

        self.add_triple(
            relay,
            "HAS_STATE",
            state
        )

        self.add_triple(
            state,
            "HAS_RSSI",
            float(row["rssi"])
        )

        self.add_triple(
            state,
            "HAS_BATTERY",
            float(row["battery"])
        )

        self.add_triple(
            state,
            "HAS_QUEUE_LENGTH",
            int(row["queue_length"])
        )

        self.add_triple(
            state,
            "HAS_MOBILITY",
            float(row["mobility"])
        )

        self.add_triple(
            state,
            "HAS_LINK_STABILITY",
            float(row["link_stability"])
        )

        self.add_triple(
            state,
            "HAS_HOP_COUNT",
            int(row["hop_count"])
        )

        self.add_triple(
            state,
            "HAS_SCORE",
            float(row["score"])
        )

        self.add_triple(
            state,
            "SELECTED",
            row["selected"] == "True"
        )

        self.add_triple(
            state,
            "AVAILABLE",
            row["available"] == "True"
        )

        # --------------------------------------------------
        # Derived contextual reasoning
        # --------------------------------------------------

        self.add_contextual_reasoning(row, state)

    def add_contextual_reasoning(self, row, state):
        """
        Analyze the current temporal relay state using the
        existing rule-based ContextualReasoner and store the
        resulting contextual knowledge as derived KG triples.
        """

        relay_id = row["relay_id"]

        state_data = {
            "relay_id": relay_id,
            "rssi": float(row["rssi"]),
            "battery": float(row["battery"]),
            "queue_length": int(row["queue_length"]),
            "mobility": float(row["mobility"]),
            "link_stability": float(row["link_stability"]),
            "hop_count": int(row["hop_count"]),
            "score": float(row["score"]),
            "available": row["available"] == "True",
            "selected": row["selected"] == "True",
        }

        analysis = self.reasoner.analyze(state_data)

        # --------------------------------------------------
        # Store contextual conditions
        # --------------------------------------------------

        context_mapping = {
            "low battery": "LOW_BATTERY",
            "sufficient battery": "SUFFICIENT_BATTERY",
            "high congestion": "HIGH_CONGESTION",
            "low queue": "LOW_QUEUE",
            "poor link stability": "POOR_LINK_STABILITY",
            "stable link": "STABLE_LINK",
            "high mobility": "HIGH_MOBILITY",
            "low mobility": "LOW_MOBILITY",
            "weak RSSI": "WEAK_RSSI",
            "strong RSSI": "STRONG_RSSI",
        }

        for reason in analysis["reasons"]:
            context = context_mapping.get(reason)

            if context is not None:
                self.add_triple(
                    state,
                    "HAS_CONTEXT",
                    context
                )

        for warning in analysis["warnings"]:
            context = context_mapping.get(warning)

            if context is not None:
                self.add_triple(
                    state,
                    "HAS_CONTEXT",
                    context
                )

        # --------------------------------------------------
        # Store contextual recommendation
        # --------------------------------------------------

        self.add_triple(
            state,
            "HAS_RECOMMENDATION",
            analysis["recommendation"]
        )

        # --------------------------------------------------
        # Store contextual score
        # --------------------------------------------------

        self.add_triple(
            state,
            "HAS_CONTEXTUAL_SCORE",
            analysis["contextual_score"]
        )

        # --------------------------------------------------
        # Store human-readable reasoning
        # --------------------------------------------------

        for reason in analysis["reasons"]:
            self.add_triple(
                state,
                "HAS_REASON",
                reason
            )

        for warning in analysis["warnings"]:
            self.add_triple(
                state,
                "HAS_WARNING",
                warning
            )

    def load_csv(self, csv_path):
        """
        Load relay observations from the simulation CSV and
        construct both raw and derived KG knowledge.
        """

        with open(csv_path, "r", newline="") as file:
            reader = csv.DictReader(file)

            for row in reader:
                self.add_relay_observation(row)

    def get_triples(self):
        return self.triples

    def save_triples(self, output_path):
        output_path = Path(output_path)
        output_path.parent.mkdir(
            parents=True,
            exist_ok=True
        )

        with open(output_path, "w", newline="") as file:
            writer = csv.writer(file)

            writer.writerow(
                [
                    "subject",
                    "predicate",
                    "object"
                ]
            )

            for triple in self.triples:
                writer.writerow(triple)


if __name__ == "__main__":
    graph = RelayKnowledgeGraph()

    graph.load_csv(
        "data/relaynet_simulation.csv"
    )

    print("==============================================")
    print("       RelayNet Knowledge Graph")
    print("==============================================")

    print(
        f"Total triples: "
        f"{len(graph.get_triples())}"
    )

    for triple in graph.get_triples()[:20]:
        print(triple)

    graph.save_triples(
        "results/relaynet_knowledge_graph.csv"
    )

    print(
        "\nKnowledge Graph exported successfully."
    )
